config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root 'registered_applications#index'
  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :registered_applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end
 
  def create
 		registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
 		if registered_application == nil
 			render json: "Unregistered application", status: :unprocessable_entity
 		else
 			@event = registered_application.events.create!(event_params)
 			if @event.save
 				render json: @event, status: :created
 			else
 				render json: {errors: @event.errors}, status: :unprocessable_entity
 			end
 		end 
  end

  def preflight
   	head 200
  end


	private

	def event_params
  	params.require(:event).permit(:name)
 	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@registered_applications = RegisteredApplication.all
	end

	def show
		@registered_application = RegisteredApplication.find(params[:id])
		@events = @registered_application.events.group_by(&:name)
	end

	def new 
		@registered_application = RegisteredApplication.new
	end

	def create
		@registered_application = RegisteredApplication.new
		@registered_application.user = current_user
    @registered_application.name = params[:registered_application][:name]
    @registered_application.url = params[:registered_application][:url]

     if @registered_application.save
      redirect_to registered_applications_path, notice: "Application was saved successfully."
     else
       flash.now[:alert] = "Error registering Application. Please try again."
       render :new
     end
	end

	def destroy
		@registered_application = RegisteredApplication.find(params[:id])

		if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
      redirect_to action: :index
     else
      flash.now[:alert] = "There was an error deleting the application."
      render :show
     end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_controller_helper.rb
module RegisteredApplicationsControllerHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">

  	<ul class="nav nav-tabs">
  	  	
    	<li><%= link_to "Home", welcome_index_path %></li>
	    <div class="pull-right user-info ">	
		    <% if user_signed_in? %>
          <%= link_to "Applications", registered_applications_path %> |
		   		Signed in as: <strong><%= current_user.email %></strong> |
		   		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - 
		   		<%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'%>
		 		<% else %>
		 			<%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <% if user_signed_in? %>
            Hello <%= current_user.first_name %>
          <% else %>
		   		  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
		 		<% end %>
		 	</div>
		</ul>


 		<div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
	</div>
</body>
</html>

app/views/registered_applications/index.html.erb
<h1>Your Registered Applications</h1>
   
  <div class="row">
    <div class="col-md-8">
      <% @registered_applications.each do |app| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to app.name, app %>
            </h4>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <%= link_to "Add Application", new_registered_application_path, class: 'btn btn-success' %>
    </div>

  </div>

app/views/registered_applications/new.html.erb
<h1> New Registered Application </h1>

<%= form_for @registered_application do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_area :url, rows: 8, class: 'form-control', placeholder: "Enter application URL" %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/registered_applications/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "path/to/highcharts.js", "chartkick" %>

<h1> <%= @registered_application.name %> </h1>
<h1> <%= @registered_application.url %> </h1>	


<%= pie_chart @registered_application.events.group(:name).count %>
<%= line_chart @registered_application.events.group_by_day(:created_at).count %>


<%= link_to "Delete Application", @registered_application, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to stop tracking this application?' } %>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmetrics</h1>